project:
  type: website
  output-dir: docs   # ⬅️ move this here!

website:
  title: "PSCH547"
  site-url: "https://apd217.github.io/PSCH547/"
  repo-url: "https://github.com/apd217/PSCH547"
  repo-actions: [edit, issue]
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: Project 1

format:
  html:
    theme: cyborg
    css: styles.css
    toc: true

editor: visual